### ISSUE TITLE
5장 서비스: 클라이언트가 파드를 검색하고 통신을 가능하게 함

### ISSUE THREAD

**Issue by leeyh2006** [leeyh2006/k8s#1]

**Comment by leeyh2006** [comment]
### 5.1 서비스 소개
쿠버네티스의 서비스는 동일한 서비스를 제공하는 파드 구룹에 지소적인 단일 접접을 만들려고 할 때 생성하는 리소스다.
 
![image](https://user-images.githubusercontent.com/25114516/224524459-7ab49d42-da9e-4fe2-9bf5-aacf4126cb61.png)

프론트엔드 파드에 관한 서비스를 만들고 클러스터 외부에서 액세스할 수 있도록 구성하면 외부 클라이언트가 파드에 연결할 수 있는 하나의 고정 IP 주소가 노출도니다. + 백엔드
- 파드의 IP 주고사 변경되더라도 서비스의 IP 주소는 변경되지 않는다.

### 5.1.1 서비스 생성
- 서비스 연결은 서비스 뒷단의 모든 파드로 로드밸런싱된다.
-  어떤 파드가 서비스의 일부분인지 레이블 샐렉터를 사용
- kubectl expose: 서비스 생성

### YAML 디스크립터를 통한 서비스 생성
```yaml
apiVersion: v1
kind: Service
metadata: 
  name: kubia
spec:
 ports: 
  - port: 80 # 서비스가 사용할 포트
     targetPort: 8080  # 서비스가 포워드할 컨테이너 포트
   selector:
     app :kubia. # app=kubia 레이블이 있는 모든 파드가 이 서비스에 포함된다.
```

서비스 조회
```
$ kubectl get svc
```

### 서비스의 세션 어피니티 구성
동일한 명령을 몇번 더 실행하면 동일한 클라이언트에서 요청하더라도 서비스 프록시가 각 연결을 임의의 파드를 선택해 연결을 다시 전달 하기 때문에 요청할 때마다 다른 파드가 선택됨.

### 동일한 서비스에서 여러개의 포트 노출
- 서비스는 단일 포트만 노출하지만 여러 포트를 지원 할 수 있음.
- 하나의 서비스를 사용해 멀티 포트 서비스를 사용하면 단일 클러스터 IP 로 모든 서비스 포트가 노출됨.

### 이름이 지정된 포트 사용
```yaml
### pod
kind: Pod
spec:
  containers:
   - name: kubia
     ports: 
     - name: http
       containerPort: 8080
     - name: https
       containerPorts: 8443
```

```yaml
Service.yaml

apiVersion: v1
kind: Service
spec:
   ports:
    - name: http
       port: 80
       targetPort: http. # 포트 80은 http 라는 컨테이너 포트에 매핑된다.

```

### 서비스 검색
#### 서비스 엔드포인트 소개
서비스 <-> 엔드포인트 <-> 파드
- 서비스의 파드 셀렉터는 엔드포인트 목록을 만드는데 사용된다.
- 엔드포인트 리소스는 서비스로 노출되는 파드의 IP 주소와 포트 목록이다.

### 인그레스가 필요한 이유
- 로드벨런서 서비스는 자신의 공용 IP 주소를 가진 로드밸런서가 필요하지만, 인그레스는 한 IP 주소로 수십 개의 서비스에 접근이 가능하도록 지원해준다.

### 파드가 연결을 수락할 준비가 됐을 때 신호 보내기
- 파드와 레이블이 서비스의 파드 셀렉터와 일치할 경우 파드가 서비스의 엔드포인트로 포함된.

### 레디니스 프로브 소개
- 쿠버네티스에서는 라이브니스 프로브와 비슷하게 파드에 레디니스 프로브를 정의 할 수 있음.
- 레드니스 프로브는 주기적으로 호출됨. 특정파드가 클라이언트 요청을 수신 할 수 있는지를 결정.
- 컨테이너의 레디니스 프로브가 성공을 반환하면 컨테이너가 요청을 수락할 준비가 됐다는 신호.

### 레디니스 프로브 유형
- 프로세스를 실행하는 Exec 프로브: 컨테이너의 상태를 프로세스의 종료 상태 코드로 결정
- HTTP GET 프로브: HTTP 상태 코드에 따른 컨테이너 준비 여부
- TCP 소켓 프로브: 컨테이너의 지정된 포트로 TCP 연결을 열고 소켓이 연결되면 준비 된것으로 간주

### 레디니스 프로브의 동작
컨테이너가 시작 -> 첫번째 호출 (기다리도록 설정가능) -> 주기적 호출 -> 파드 준비시 서비스 추가
- 라이브니스 프로브와 차이는 컨테이너가 준비 상태 점검에 실패하더라도 컨테이너가 종료되거나 다시 시작되지 않음. (요청을 처리할 준비가 된 파드의 컨테이너만 요청을 수신하도록 함)
![image](https://user-images.githubusercontent.com/25114516/224766272-e27f2025-a0f8-4414-87bd-4096de137a80.png)


### 서비스 문제 해결
- 외부가 아닌 클러스터 내에서 서비스의 클러스터 IP에 연결이 되는지 확인
- 서비스의 클러스터 IP는 가상 IP이므로 핑이 되지 않음.
- 레디니스 프로브를 정의 했으면 성공했는지 확인.
- 파드가 서비스의 일부인지 확인하려면 endpoints 오브젝트를 조회해라.
