### ISSUE TITLE
3장 파드: 쿠버네티스에서 컨테이너 실행

### ISSUE THREAD

**Issue by leeyh2006** [leeyh2006/k8s#2]

**Comment by leeyh2006** [comment]
### 파드 이해하기
- 여러 프로세스를 단일 컨테이너로 묶지 않기 때문에, 컨테이너를 함께 묵고 하나의 단위로 관리 할 수 있는 또 다른 상위 구조가 필요.
- 단일 컨테이너 안에서 모두 함께 실행되는 것처럼 동일한 환경을 제공 할 수 있으면 이들을 격리된 상태로 유지 가능.
- 쿠버네티스는 파드 안에 있는 모든 컨테이너가 자체 네임스페이스가 동일한 리눅스 네임스페이스를 공유하도록 도커를 설정

### 파드를 정의하는 주요 부분 소개
- Metadata: 이름 네임스페이스, 레이블 및 파드에 관한 기타 정보를 포함
- Spec: 파드 컨테이너, 볼륨 기타 데이터 등 파드 자체에 관한 실제 명세를 가진다.
- Status: 파드 상태, 각 컨테이너 설명과 상태, 파드내부 IP, 기타 기본 정보 등 현재 실행 중인 파드에 관한 현재 정보를 포함한다.

### 간단 예제
```yaml
apiVersion: v1
Kind: Pod
metadata: 
  name: kubia-manual
spec:
  containers:
  - image: luksa/kub
    name: kubia
    ports:
    - containerPort: 8080
       protocol: TCP
```

### kubectl 명령어
```
$ kubectl create -f example.yaml // 파드 생성하기
$ kubectl get po kubia-manual -o yaml // 파드 전체 정의
$ kubectl get pods // 파드 조회
```

### 애플리케이션 로그 보기
- `kubectl logs {pod_name} -c {container_name}` 
- 컨테이너 로그는 하루 단위로 로그 파일이 10MB 크기에 도달할 때마다 순환된다.

### 레이블 소개
- 레이블은 파드와 모든 다른 쿠버네티스 리소를 조직화 할 수 있는 단순하면서 강력한 쿠버네티스 기능이다.
- 레이블은 리소스에 첨부하는 키-값 쌍으로, 이 상은 레이블 셀렉터를 사용해 리소를 선택할 때 활용된다.
