### ISSUE TITLE
6장 볼륨: 컨테이너에 디스크 스토리지 연결

### ISSUE THREAD

**Issue by leeyh2006** [leeyh2006/k8s#3]

**Comment by leeyh2006** [comment]
### 스토리지 볼륨
- 파드 내부의 각 컨테이너는 고유하게 분리된 파일 시스템을 가진다.
- 실제 데이터를 가진 디렉터리를 보존하고 싶을 경우 정의
- 스토리지 볼륨은 파드와 같은 최상위 리소스는 아니지만 파드의 일부분으로 정의되며 파드와 동일한 라이프 사이클을 가짐.
- 파드시작 -> 볼륨생성, 파드삭제 -> 볼륨삭제
- 파드가 여러개의 컨테이너를 가진 경우 모든 컨테이너가 볼륨을 공유 할 수 있음.

### 6.1 볼륨 소개
- 파드의 구성요소 컨테이너와 동일하게 파드 스페에서 정의됨.
- 볼륨은 독립적인 쿠버네티스 오브젝트가 아니므로 자체적으로 생성, 삭제될 수 없음.
- 볼륨은 파드의 모든 컨테이너에서 사용 가능, but 컨테이너에서 각각 마운트 되야함.

ex) 파드 내 컨테이너 3개 볼륨 2개 마운트 
![image](https://user-images.githubusercontent.com/25114516/225965049-232ed958-06a0-493a-8659-1044e5d6dd30.png)

### 6.1.2 사용 가능한 볼륨 유형 소개
- emptyDir: 일시적인 데이터를 저장하는데 사용되는 빈 디렉터리
- hostPath: 워커 노드의 파일 스시템을 파드의 디렉터리로 마운트하는데 사용
- gitRepo: git checkout 볼륨
- nfs: NFS 공유를 파드에 마운트
- configMap, secret, downardAPI: 쿠버네티스 리소스나 클러스터 정보를 파드에 노출하는 데 사용되는 볼륨
- persitentVolumeClaim: 사전에 혹은 동적으로 프로비저닝된 퍼시스턴트 스토리지를 사용하는 방법

### emptyDir
- 빈디렉터리로 볼륨이 시작
- 동일 파드에서 실행중인 컨테이너 간 파일을 공유 할때 유용(?) 어떤케이스가 있을까.

Ex) 웹 서버 컨테이너와 콘텐츠 에이전트, HTML을 위한 단일 볼륨으로 파드 구성
<details>
<summary>example.yaml</summary>

```yaml

apiVersion: v1
kind: Pod
metadata:
  name: fortune
spec:
  containers:
    - image: ~
    name: html-generator
    volumeMounts: # html이란 이름의 볼륨을 컨테이너의 /var/htdocs dp akdnsxm
      name: html
      mountPath: /var/htdocs
    - image: nginx
    name: web-server
    volumeMounts: 
      - name: html  # 위와 동일한 볼륨을 /usr/share/nginx/html 에 읽기 전용으로 마운트한다.
        mountPath: /usr/share/nginx/html 
        readOnly: true 
volumes: # html이란 단일 emptyDir 볼륨을 위의 컨테이너 두 개에 마운트한다.
  - name: html
    emptyDir: {}
```

</details>

### emptyDir 을 사용하기 위한 매체 지정하기
- 쿠버네티스에 emptyDir을 디스크가 아닌 메모리를 사용하는 tmpfs 파일 시스템으로 생성하도록 요청 가능

```yaml
volumes: 
  - name: html
    emptyDir:
       medium: Memory # 메모리에 저장됨.
```

### 6.2.2 깃 레포를 볼륨으로 사용하기
- `gitRepo` 볼륨은 기본적으로 `emptyDir` 볼륨이며 파드가 시작되면 깃 레포지터리를 복제하고 특정 리비전을 체크아웃해 데이터로 체음.

### 6.3 워커 노드 파일 시스템의 파일 접근
### 6.3.1 hostPath 볼륨
- 노드의 특정파일, 디렉터리를 가리킴
- gitRepo, emptyDir 과 다르게 파드가 종료되도 삭제되지 않음.
- 노드의 시스템 파일에 읽기/쓰기를 하는 경우에만 `hostPath` 볼륨을 사용, 여러 파드에 걸쳐 데이터를 유지하기 위해서는 절대 사용 하지말라

### 6.4 퍼시스턴트 스토리지 사용
- GCE 퍼시스턴트 디스크를 파드 볼륨으로 사용 (
- 프로비저닝: 프로비저닝은 사용자의 요구에 맞게 시스템 자원을 할당, 배치, 배포

**Comment by leeyh2006** [comment]
6.5 기반 스토리지 기술과 파드 분리
6.5.1 퍼시스턴트 볼륨과 퍼시스턴트볼륨 클레임
PV - 관리가자가 물리적인 공간을 클러스터에 생성 (프로바이저닝된 PV)
PVC - 사용자가 클러스터 내부에서 관리자가 생성해놓은 PV에 PVC 를 바인딩

### 퍼시스턴트 볼륨 클레임 생성하기
```yaml


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  resources:
    requests:
      storage: 1Gi   # 1GiB의 스토리지를 요청한다.
  accessModes: 
  - ReadWriteOnce # 단일 클라이언트를 지원하는 스토리지다. (읽기/쓰기를 모두 수행한다.)
  StorageClassName: "" 

NAME       STATUS   VOLUME     CAPACITY   ACCESS MODES   AGE
pvc             Bound       pvc                1Gi             RWO, ROX             3s       
```
- RWO: 단일 노드만이 읽기/쓰기용으로 볼륨을 마운트 
- ROX(ReadOnlyMany): 다수 노드가 읽기용으로 볼륨을 마운트
- RWX: 다수노드 읽기/쓰기 용으로 마운트

### 파드에서 PVC 참조하기
```yaml
volumes:
- name: mognodb-data
   persistnetnVolumeClaim: 
      claimName: mongodb-pvc.  # 파드 볼륨에서 이름으로 퍼시스턴트 볼륨클레임을 참조.
```

### pv 와 pvc 의 장점
- 개발자는 기저에 사용된 실제 스토리지 기술을 알필요 없다. (pvc 로 연결해서 사용)
- 동일한 파드와 클레임 매니페스트는 인프라스트럭처와 관련된 어떤 것도 참조 하지 않으므로 다른 쿠버네티스 클러스터에서도 사용할 수 있다.
