### ISSUE TITLE
9장 디플로이먼트

### ISSUE THREAD

**Issue by leeyh2006** [leeyh2006/k8s#5]
### 9.1.2 새파드 기동과 이전 파드 삭제
- 다운타임이 발생하지 않음.
- 기존 파드와 새파드가 같이 공존하기 때문에 하드웨어 리소스가 더 많이 필요.
- 블루그린: 새파드가 모두 실행되면 서비스의 레이블 셀렉터를 변경하고 서비스를 새 파드로 전환
- 롤링 업데이트

### 9.2 레플리케이션 컨트롤러로 자동 롤링 업데이트 수행
```
$ kubectl rolling-update  ${v1_name} ${v2_name} --image=name
```
But 사용하지 않음
-> k8s 가 직접 파드의 레이블과 레플리케이션컨트롤러의 레이블 셀렉터를 수정하는것은 예상치 못한 문제를 발생 시킬 수 있음.

### 애플리케이션을 선언적으로 업데이트 하기 위한 디플로이먼트 사용하기
디플로이먼트: 애플리케이션을 배포하고 선언적으로 업데이트하기 위한 높은수준의 리소스
디플로이먼트 -> 레플리카셋 -> 파드,파드,파드...

why 디플로이먼트 ?
- 애플리케이션을 업데이트 할때는 추가 레플리케이션 컨트롤러를 도입하고, 두 컨트롤러가 잘 조화되도록 조정해야함. 이런것을 디플로이먼트가 통제 

### 디플로이먼트 생성
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
spec:
  replicas: 3
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
        - image: luksa/kubia:v1
          name: nodejs
```

### 디플로이먼트가 레플리카셋을 생성하는 방법과 레플리카셋이 파드를 생성하는 방식 
디플로이먼트가 생성한 파드이름은 해시값이 추가되면서 지어짐. (디플로이먼트와 파드 템플릿의 해시값을 의미, 레플리카셋이 이러한 파드를 관리)

```

# 레플리카셋의 이름이 파드 템플릿의 해시값이 포함됨.
$ kubectl get rc
kubia-1111

$ kubectl get pods
kubia-1111-asdf
kubia-1111-rerer
kubia-1111-qwer

```

### 레플리케이션 컨트롤러 대신 디플로이먼트를 사용해야하는 이유
- 롤링업데이트 대체되는 새 레플리에키션컨트롤러의 이름을 지정해야했음. 디플로이먼트는 리소스에 정의된 파드 템플릿을 수정하기만 하면됨.

```
ex) 이미지 교체 
kubectl set image deployment kubia nodejs=luksa/kubia:v2
```
